name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

defaults:
  run:
    shell: bash --noprofile --norc -Eeuo pipefail {0}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Verify Swift
        run: swift --version

      - name: Build
        run: swift build
